---
title: "CBS Update"
author: "Marino van Zelst"
date: "19-6-2020"
output: word_document
---

```{r analyses, echo=FALSE, message=FALSE, error=FALSE, tidy=TRUE,warning=FALSE,eval=TRUE}
require(stringr)
require(tidyr)
require(cbsodataR)
require(reshape2)
require(lubridate)
require(rvest)
require(rtweet)

weeknumber <- isoweek(ymd(Sys.Date()))-2

table_mortality <- cbs_get_data("70895ned", Perioden = has_substring(c("2013","2014","2015","2016","2017","2018","2019","2020")), Geslacht = has_substring("1100"))
table_mortality$Year <- substr(table_mortality$Perioden, 1, 4)

table_mortality$Week <- str_sub(table_mortality$Perioden, start = -2)

table_mortality$LeeftijdOp31December <- factor(table_mortality$LeeftijdOp31December, levels = c(10000, 41700, 53950, 21700),
                                               labels = c("Totaal","0 tot 65", "65 tot 80", "80+"))

bevolking <- cbs_get_data("37296ned", Perioden = has_substring(c("2013JJ00","2014JJ00","2015JJ00", "2016JJ00","2017JJ00","2018JJ00","2019JJ00")))
bevolking <- bevolking[,c("Perioden","TotaleBevolking_1", "JongerDan20Jaar_10","k_20Tot40Jaar_11","k_40Tot65Jaar_12","k_65Tot80Jaar_13","k_80JaarOfOuder_14")]

colnames(bevolking) <- c("Jaar","Totaal","Jonger20","20tot40","40tot65","65tot80","80ouder")

bevolking$jonger65 <- bevolking$Jonger20 + bevolking$`20tot40` + bevolking$`40tot65`
bevolking <- bevolking[,c("Jaar","Totaal","jonger65","65tot80","80ouder")]
colnames(bevolking) <- c("Year","Totaal","0 tot 65","65 tot 80","80+")
bevolking$Year <- substr(bevolking$Year, 1, 4)

bevolking2020 <- data.frame(c("2020","17414600","14015030", "2570467", "822088"))

bevolking <- rbind(bevolking, c("2020","17414600","14015030", "2570467", "822088"))



bevolking <- gather(bevolking,"LeeftijdOp31December","Bevolking",2:5)

bevolking$Bevolking <- as.numeric(bevolking$Bevolking)


## Select weeks
table_mortality <- subset(table_mortality, Week > 00 & Week < weeknumber+1)
table_mortality <- table_mortality[!table_mortality$Week == '00',]



mortality_full <- merge(table_mortality, bevolking, by=c("Year","LeeftijdOp31December"), all.x=TRUE)

bevolking2020 <- data.frame(Bevolking2020=c(14015030, 2570467, 822088, 17414600),
                            LeeftijdOp31December=c("0 tot 65","65 tot 80","80+","Totaal"))

mortality_full <- merge(mortality_full, bevolking2020, by=c("LeeftijdOp31December"))
mortality_full$Overledenen_1 <- mortality_full$Overledenen_1/mortality_full$Bevolking*mortality_full$Bevolking2020

mortality_wide <- dcast(mortality_full, LeeftijdOp31December + Week ~ Year, value.var = "Overledenen_1", sum)

mortality_wide$Average20152019 <- rowMeans(mortality_wide[,c("2015","2016","2017","2018","2019")])
mortality_wide$Average20132017 <- rowMeans(mortality_wide[,c("2013","2014","2015","2016","2017")])

mortality_wide$excess_death <- mortality_wide$`2020` - mortality_wide$Average20152019

mortality_wide$excess_flu <- mortality_wide$`2018` - mortality_wide$Average20132017


```

```{r data prep, echo=FALSE, message=FALSE, error=FALSE, tidy=TRUE,warning=FALSE,eval=TRUE}


week.benchmark <- round(mortality_wide[which(mortality_wide$Week == weeknumber & mortality_wide$LeeftijdOp31December == "Totaal"),"Average20152019"],0)

week.2020 <- round(mortality_wide[which(mortality_wide$Week == weeknumber & mortality_wide$LeeftijdOp31December == "Totaal"),"2020"],0)

## Calculate official death numbers
rivm.data <- read.csv("https://data.rivm.nl/covid-19/COVID-19_casus_landelijk.csv", sep=";")
rivm.data <- rivm.data %>%
  dplyr::filter(Deceased == "Yes")
rivm.data$Week <- substr(rivm.data$Week_of_death, 5, 6)
rivm.data$deaths_rivm <- 1

rivm_deaths <- aggregate(deaths_rivm ~ Week, data = rivm.data, FUN = sum)
rivm_thisweek <- rivm_deaths[which(rivm_deaths$Week == weeknumber),"deaths_rivm"]
```



```{r excess deaths, echo=FALSE, message=FALSE, error=FALSE, tidy=TRUE,warning=FALSE,eval=TRUE}
alleen_oversterfte <- subset(mortality_wide, Week > 11 & Week < 20)
excess_deaths <- aggregate(excess_death ~ LeeftijdOp31December, data = alleen_oversterfte, FUN = sum)
age_corrected.excess <- round((sum(excess_deaths$excess_death) - excess_deaths[excess_deaths$LeeftijdOp31December == "Totaal","excess_death"]),0)
historic.average.excess <- round(sum(excess_deaths$excess_death) - age_corrected.excess,0)

## Pull CBS data
u <- "https://www.cbs.nl/nl-nl/faq/corona/medisch/hoeveel-sterfgevallen-zijn-er-per-week"
webpage <- read_html(u)
cbs.tables <- html_table(webpage, fill=TRUE)
cbs.df <- as.data.frame(cbs.tables[1])
cbs.df <- cbs.df %>%
  dplyr::filter(Week > 11 & Week < (weeknumber + 1) & Week != 2)

cbs.df$verwacht.aantal.overledenen.2020 <- as.numeric(cbs.df$verwacht.aantal.overledenen.2020)
cbs.df$X2020. <- as.numeric(cbs.df$X2020.)

cbs.df$excess_death <- cbs.df$X2020. - cbs.df$verwacht.aantal.overledenen.2020
cbs.oversterfte <- subset(cbs.df, Week > 11 & Week < 20)
cbs.method.excess <- sum(cbs.oversterfte$excess_death)
```

```{r ondersterfte, echo=FALSE, message=FALSE, error=FALSE, tidy=TRUE,warning=FALSE,eval=TRUE}
alleen_ondersterfte <- subset(mortality_wide, Week > 19)
less_deaths <- aggregate(excess_death ~ LeeftijdOp31December, data = alleen_ondersterfte, FUN = sum)
age_corrected_less <- round((sum(less_deaths$excess_death) - less_deaths[less_deaths$LeeftijdOp31December == "Totaal","excess_death"]),0)
historic.average_less <- round(sum(less_deaths$excess_death) - age_corrected_less,0)

cbs.ondersterfte <- subset(cbs.df, Week > 19)
cbs.method_less <- sum(cbs.ondersterfte$excess_death)


data.currentweek <- subset(mortality_wide, Week > (weeknumber -1))
excess_thisweek <- aggregate(excess_death ~ LeeftijdOp31December, data = data.currentweek, FUN = sum)
deaths_thisweek <- sum(excess_thisweek$excess_death) - round(excess_thisweek[excess_deaths$LeeftijdOp31December == "Totaal","excess_death"],0)

griep <- subset(mortality_wide, Week > 13)
excess_flu <- aggregate(excess_flu ~ LeeftijdOp31December, data = griep, FUN = sum)
age_corrected.flu <- round((sum(excess_flu$excess_flu) - excess_flu[excess_flu$LeeftijdOp31December == "Totaal","excess_flu"]),0)

griep.sameweeks <- subset(mortality_wide, Week > 13 & Week < 20)
excess_flu.sameweeks <- aggregate(excess_flu ~ LeeftijdOp31December, data = griep.sameweeks, FUN = sum)
age_corrected.flu.samenweeks <- round((sum(excess_flu.sameweeks$excess_flu) - excess_flu.sameweeks[excess_flu.sameweeks$LeeftijdOp31December == "Totaal","excess_flu"]),0)



```


```{r tweets, echo=FALSE, eval=TRUE}
tweet1 <- paste0("CBS heeft het aantal overlijdensgevallen bijgewerkt t/m week ",weeknumber," van dit jaar. Deze week combineer ik de grafieken over sterfte per week (alleen totaal) met een uitgebreide ondersterfte vergelijking tussen 2018 en 2020. Ik kijk ook naar de oversterfte in Europa.")

tweet2 <- "De data komt hier vandaan: https://www.cbs.nl/nl-nl/cijfers/detail/70895ned. Ik gebruik de data van 2015-2019. Week 1, 52, en 53 zijn eruit gehaald omdat dit regelmatig halve weken zijn en dat creëert enigszins ruis. Data die ik gebruik voor de analyses vind je hier: https://surfdrive.surf.nl/files/index.php/s/QECTNiYZqdGyWL4"

tweet3 <- "Ik publiceer de oversterfte analyses volgens drie methodes: een historisch gemiddelde (1), de oversterfte per leeftijdsgroep omdat je daarmee beter corrigeert voor vergrijzing (2) en methode CBS (3). Groeifactor model publiceer ik niet meer, uitleg hier: https://twitter.com/mzelst/status/1266333188386848768"

tweet4 <- "Ik splits de analyses voor de weken waarin er oversterfte was (week 12 t/m 19) en de weken met ondersterfte (vanaf week 20). De grafiek hieronder loopt op de verticale as van 2000-5000, zodat je de verschillen tussen de weken beter kunt zien."

tweet5 <- paste0("Sterfte per week: De blauwe piek die je ziet is 2020. Gemiddeld aantal overledenen in week ", weeknumber," (2015-2019) is ",week.benchmark,", 2020 = ",week.2020,". RIVM zegt nu ",rivm_thisweek," in week ",weeknumber,". Er is dus ondersterfte in week ",weeknumber,", zelfs met ",rivm_thisweek," officiële corona-overledenen (wat waarschijnlijk niet eens alles is).")

tweet6 <- paste0("Oversterfte NL: Voor week 12 t/m 19 voorspelden de verschillende methodes dit: (1) ",historic.average.excess, ", (2) ",age_corrected.excess,
                 ", en (3) ",cbs.method.excess,
                 ". Ik houd de oversterfte in de 'heftige' periode dus op ",age_corrected.excess, 
                 "-",historic.average.excess,".")

tweet7 <- paste0("Op basis van methode (2) is in week ",weeknumber," de ondersterfte ",round(deaths_thisweek,0),
                 ". Ondersterfte vanaf week 20 t/m ",weeknumber,": (1) ", historic.average_less,
                 ", (2) ",age_corrected_less," en (3) ",cbs.method_less,". Ik houd de totale sterfte (week 12 t/m ",
                 weeknumber,") op dit moment tussen de ",age_corrected.excess + age_corrected_less,"-",
                 historic.average.excess + historic.average_less,".")

tweet8 <- "In 2018 was er een zware griepepidemie waarna er ook een periode was van langdurige ondersterfte. Om die periode te vergelijken met de huidige weken, heb ik de ondersterfte in 2018 berekend op basis van 2013-2017 (uiteraard met correctie per leeftijdsgroep)."

tweet9 <- paste0("De ondersterfte begon in 2018 vanaf week 14 voor alle leeftijdsgroepen. De ondersterfte van week 14 t/m ",weeknumber," was ",age_corrected.flu," (flink hoger dan in 2020). Maar dat is uiteraard ondersterfte over meer weken, namelijk ",weeknumber-14,". Dus wat als we net als in 2020 de eerste ",weeknumber-19," weken van 2018 pakken?")

tweet10 <- paste0("Als we het aantal weken ondersterfte gelijkzetten (zodat we de 'snelheid' waarmee oversterfte 'gecorrigeerd' wordt kunnen vergelijken), gebruiken we nu ",weeknumber-19," weken. De ondersterfte in 2020 gaat nu dus sneller dan in 2018 (",age_corrected_less," vs. ",age_corrected.flu.samenweeks,"). Het is afwachten of deze trend doorzet.")

tweet11 <- paste0("Europa week ",weeknumber+1,": Een aantal landen laten weer wat oversterfte zien (Belgie, Zweden, Spanje, en zeker Portugal), maar Europees breed blijft het gelijk. Totale oversterfte week 12 t/m ",weeknumber+1," = 170000")

tweet12 <- paste0("Conclusie na week ",weeknumber,": we zitten in een periode van ondersterfte (dat is normaal na een heftige epidemie, zoals ik deze week cijfermatig laat zien), waarbij de ondersterfte snel toeneemt. Afhankelijk van het type zomer kan dit ook wel flink doorzetten, maar dat is afwachten.")

tweet13 <- "Eindnoot 1: dit draadje is een mix van eigen analyses en inspiratie vanuit dit mooie overzicht van The Economist: https://www.economist.com/graphic-detail/2020/04/16/tracking-covid-19-excess-deaths-across-countries The Economist en het FT publiceren hun data open source voor geinteresseerden: https://github.com/Financial-Times/coronavirus-excess-mortality-data"

tweet14 <- "Eindnoot 2: Voor de geinteresseerden, de R code die ik hiervoor gebruik is hier te vinden: https://github.com/mzelst/covid-19. Het draadje wordt nu ook gepost vanuit R. Ik publiceer hier ook dagelijkse updates met @edwinveldhuizen en zet deze data ook online."

tweet15 <- "Eindnoot 3: Ik dank @statistiekcbs voor het publiceren van een R package, waardoor dit compleet geautomatiseerd kan :) En dank aan alle andere corona-dataverwerkers! Rutte geparafraseerd: 'Alleen samen krijgen we corona-data onder controle.'"

tweet1

tweet2

tweet3

tweet4

tweet5

tweet6

tweet7

tweet8

tweet9

tweet10

tweet11

tweet12

tweet13

tweet14

tweet15

```

```{r post tweets, eval=FALSE}
post_tweet(status=tweet1)

## lookup status_id
my_timeline <- get_timeline(rtweet:::home_user())
## ID for reply
reply_id <- my_timeline$status_id[1]
## post reply
post_tweet(tweet2,in_reply_to_status_id = reply_id)

## lookup status_id
my_timeline <- get_timeline(rtweet:::home_user())
## ID for reply
reply_id <- my_timeline$status_id[1]
## post reply
post_tweet(tweet3,in_reply_to_status_id = reply_id)

## lookup status_id
my_timeline <- get_timeline(rtweet:::home_user())
## ID for reply
reply_id <- my_timeline$status_id[1]
## post reply
post_tweet(tweet4,in_reply_to_status_id = reply_id)

## lookup status_id
my_timeline <- get_timeline(rtweet:::home_user())
## ID for reply
reply_id <- my_timeline$status_id[1]
## post reply
post_tweet(tweet5,media="C:/Users/s379011/surfdrive/projects/2020covid-19/graphs_excess_mortality/overledenen_thisweek.png",in_reply_to_status_id = reply_id)

## lookup status_id
my_timeline <- get_timeline(rtweet:::home_user())
## ID for reply
reply_id <- my_timeline$status_id[1]
## post reply
post_tweet(tweet6,in_reply_to_status_id = reply_id)

## lookup status_id
my_timeline <- get_timeline(rtweet:::home_user())
## ID for reply
reply_id <- my_timeline$status_id[1]
## post reply
post_tweet(tweet7,in_reply_to_status_id = reply_id)

## lookup status_id
my_timeline <- get_timeline(rtweet:::home_user())
## ID for reply
reply_id <- my_timeline$status_id[1]
## post reply
post_tweet(tweet8,in_reply_to_status_id = reply_id)

## lookup status_id
my_timeline <- get_timeline(rtweet:::home_user())
## ID for reply
reply_id <- my_timeline$status_id[1]
## post reply
post_tweet(tweet9,in_reply_to_status_id = reply_id)

## lookup status_id
my_timeline <- get_timeline(rtweet:::home_user())
## ID for reply
reply_id <- my_timeline$status_id[1]
## post reply
post_tweet(tweet10,in_reply_to_status_id = reply_id)

## lookup status_id
my_timeline <- get_timeline(rtweet:::home_user())
## ID for reply
reply_id <- my_timeline$status_id[1]
## post reply
post_tweet(tweet11,media="C:/Users/s379011/surfdrive/projects/2020covid-19/graphs_excess_mortality/EuroMOMO_thisweek.png",in_reply_to_status_id = reply_id)

## lookup status_id
my_timeline <- get_timeline(rtweet:::home_user())
## ID for reply
reply_id <- my_timeline$status_id[1]
## post reply
post_tweet(tweet12,in_reply_to_status_id = reply_id)

## lookup status_id
my_timeline <- get_timeline(rtweet:::home_user())
## ID for reply
reply_id <- my_timeline$status_id[1]
## post reply
post_tweet(tweet13,in_reply_to_status_id = reply_id)

## lookup status_id
my_timeline <- get_timeline(rtweet:::home_user())
## ID for reply
reply_id <- my_timeline$status_id[1]
## post reply
post_tweet(tweet14,in_reply_to_status_id = reply_id)

## lookup status_id
my_timeline <- get_timeline(rtweet:::home_user())
## ID for reply
reply_id <- my_timeline$status_id[1]
## post reply
post_tweet(tweet15,in_reply_to_status_id = reply_id)


```

